// Code generated by lister-gen. DO NOT EDIT.

package v1

// EtcdClusterListerExpansion allows custom methods to be added to
// EtcdClusterLister.
type EtcdClusterListerExpansion interface{}

// EtcdClusterNamespaceListerExpansion allows custom methods to be added to
// EtcdClusterNamespaceLister.
type EtcdClusterNamespaceListerExpansion interface{}
