// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/xing393939/samplecrd-code/pkg/clients/etcdcluster/clientset/versioned/typed/etcdcluster/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeSamplecrdV1 struct {
	*testing.Fake
}

func (c *FakeSamplecrdV1) EtcdClusters(namespace string) v1.EtcdClusterInterface {
	return &FakeEtcdClusters{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeSamplecrdV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
